In [3]:
import numpy as np


In [4]:
a=np.array([1,2,34,5])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.ndim

1

In [7]:
a.shape

(4,)

In [8]:
a.itemsize

4

In [9]:
a=np.arange(5*4).reshape((5,4))

In [10]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [11]:
a=np.arange(5*4,dtype=float).reshape((5,4))

In [12]:
a

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]])

In [13]:
a.itemsize

8

In [14]:
a.sum

<function ndarray.sum>

In [15]:
a.sum()

190.0

In [16]:
a=np.arange(5,dtype=complex)

In [17]:
a

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [18]:
a.itemsize

16

In [19]:
a=np.arange(1,5,2)

In [20]:
a

array([1, 3])

In [21]:
np.arange(1,10,5)

array([1, 6])

In [22]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [23]:
a=np.arange(10).reshape(5,2)

In [24]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [25]:
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [27]:
a.reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [28]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [29]:
a=np.arange(16).reshape((4,4))

In [30]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
a.min()

0

In [32]:
a.max()

15

In [33]:
a.sum()

120

In [34]:
a.sum(axis=0)   #col sum

array([24, 28, 32, 36])

In [35]:
a.sum(axis=1)    # row sum

array([ 6, 22, 38, 54])

In [36]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335]])

In [37]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
np.std(a)

4.6097722286464435

In [39]:
b=np.arange(20,36).reshape((4,4))

In [40]:
b

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [41]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
a+b

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 50]])

In [43]:
a*b

array([[  0,  21,  44,  69],
       [ 96, 125, 156, 189],
       [224, 261, 300, 341],
       [384, 429, 476, 525]])

In [44]:
a/b

array([[0.        , 0.04761905, 0.09090909, 0.13043478],
       [0.16666667, 0.2       , 0.23076923, 0.25925926],
       [0.28571429, 0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471, 0.42857143]])

In [45]:
a//b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [46]:
a%b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]], dtype=int32)

In [47]:
b%a

C:\Users\Dell\AppData\Local\Temp\ipykernel_16392\2686318045.py:1: RuntimeWarning: divide by zero encountered in remainder
  b%a


array([[0, 0, 0, 2],
       [0, 0, 2, 6],
       [4, 2, 0, 9],
       [8, 7, 6, 5]], dtype=int32)

In [48]:
a[0][0]=1

In [49]:
a

array([[ 1,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
b/a

array([[20.        , 21.        , 11.        ,  7.66666667],
       [ 6.        ,  5.        ,  4.33333333,  3.85714286],
       [ 3.5       ,  3.22222222,  3.        ,  2.81818182],
       [ 2.66666667,  2.53846154,  2.42857143,  2.33333333]])

In [51]:
b//a

array([[20, 21, 11,  7],
       [ 6,  5,  4,  3],
       [ 3,  3,  3,  2],
       [ 2,  2,  2,  2]], dtype=int32)

In [52]:
a.dot(b)

array([[ 196,  203,  210,  217],
       [ 592,  614,  636,  658],
       [1008, 1046, 1084, 1122],
       [1424, 1478, 1532, 1586]])

In [53]:
a

array([[ 1,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
b

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [55]:
np.multiply(a,b)

array([[ 20,  21,  44,  69],
       [ 96, 125, 156, 189],
       [224, 261, 300, 341],
       [384, 429, 476, 525]])

In [56]:
b[0]

array([20, 21, 22, 23])

In [57]:
b.sum(axis=0)

array([104, 108, 112, 116])

In [58]:
b.sum(axis=1)

array([ 86, 102, 118, 134])

In [59]:
b[0]

array([20, 21, 22, 23])

In [60]:
b[0,2]

22

In [61]:
b[:,2]

array([22, 26, 30, 34])

In [62]:
np.vstack((a,b)

array([[ 1,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [63]:
np.vstack((a,b))

array([[ 1,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [64]:
np.hstack((a,b))

array([[ 1,  1,  2,  3, 20, 21, 22, 23],
       [ 4,  5,  6,  7, 24, 25, 26, 27],
       [ 8,  9, 10, 11, 28, 29, 30, 31],
       [12, 13, 14, 15, 32, 33, 34, 35]])

In [65]:
np.hsplit(a,2)

[array([[ 1,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [66]:
a

array([[ 1,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [67]:
np.vsplit(a,2)

[array([[1, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [68]:
np.vsplit(a,4)

[array([[1, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [69]:
a>b

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [70]:
b>a

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [73]:
np.random.rand(1,10)

array([[0.08738636, 0.33634851, 0.7319355 , 0.47706731, 0.01490803,
        0.17628216, 0.890699  , 0.08510409, 0.70499922, 0.14635302]])

In [74]:
np.random.randint(1,10)

2

In [75]:
a=np.random.randint(1,16,size=16).reshape(4,4)

In [76]:
a

array([[ 7, 13,  2, 14],
       [12,  3, 14, 11],
       [ 6,  1,  7,  8],
       [11, 14, 12, 12]])

In [77]:
b=np.random.randint(1,16,size=16).reshape(4,4)

In [78]:
b

array([[11,  6, 15,  4],
       [12,  4, 13, 10],
       [14, 12, 14,  1],
       [11,  9, 13, 10]])

In [79]:
c=a>b

In [80]:
c

array([[False,  True, False,  True],
       [False, False,  True,  True],
       [False, False, False,  True],
       [False,  True, False,  True]])

In [81]:
a[c]

array([13, 14, 14, 11,  8, 14, 12])

In [82]:
r=np.nditer(a,order="c")

In [83]:
r

In [84]:
for i in r:
    print(i)

7
13
2
14
12
3
14
11
6
1
7
8
11
14
12
12


In [85]:
r=np.nditer(a,order="f")

In [98]:
for i in r:
    print(i)

5
7
8
5
15
3
6
8
12
15
11
1
12
3
5
12
